app/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'app.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

  url(r'^$', include('phm.urls')),
  url(
    r'^favicon.ico$',
    RedirectView.as_view(
      url='/static/images/favicon.ico',
      permanent=False),
    name="favicon"
  ),
  url(r'^phm/', include('phm.urls')),
  url(r'^admin/', include(admin.site.urls)),
)

handler404 = 'app.views.custom_page_not_found'
handler500 = 'app.views.custom_server_error'

phm/urls.py
from django.conf.urls import patterns, url

from phm import views

urlpatterns = patterns('',
  url(r'^$', views.index, name='index'),
  url(r'^addproject', views.addproject, name='addproject'),
  url(r'^allprojects', views.listallprojects, name='listallprojects'),
  url(r'^addcheckin', views.addcheckin, name='addcheckin'),
  url(r'^viewproject', views.listallprojects, name='project'),
  url(r'^editproject', views.editproject, name='editproject'),
  url(r'^project', views.project, name='project'),
  url(r'^auth', views.auth_screen, name='auth_screen'),
  url(r'^oauth2callback', views.oauth2callback, name='oauth2callback'),
  url(r'^logout$', views.phm_logout, name='phm_logout'),
  url(r'^checkin_past', views.checkin_past, name='checkin_past'),
  url(r'^about$', views.about, name='about'),
  url(r'^staff', views.get_staff, name='get_staff'),
  url(r'^getprojects', views.get_projects, name='get_projects'),
  url(r'^departments', views.get_departments, name='get_departments'),
  url(r'^hashemail', views.hash_email, name='hash_email'),
  url(r'^favourites', views.favourites, name='favourites'),
  url(r'^favourite', views.favourite, name='favourite')
)

phm/models.py
from django.db import models

class User(models.Model):
    fullName = models.CharField(max_length=60, null=True)
    username = models.CharField(max_length=40, null=True, blank=True)
    email = models.CharField(max_length=60, null=True)

    def __str__(self):
        return self.fullName

class Department(models.Model):
    name = models.CharField(max_length=60, primary_key=True)
    is_active = models.BooleanField(default=True)

class Project(models.Model):
    name = models.CharField(max_length=30)
    link = models.TextField(null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    owner = models.ForeignKey(User, related_name="owner")
    sponsor = models.ForeignKey(User, related_name="sponsor")
    nextCheckIn = models.DateTimeField(null=True, blank=True)
    department = models.CharField(max_length=60, null=True, blank=True)
    avatar = models.ImageField("Project Avatar", upload_to="images/", blank=True, null=True)

    def __str__(self):
        return self.name

class Favourites(models.Model):
    user_id = models.ForeignKey(User)
    project_id = models.ForeignKey(Project)

class CheckIn(models.Model):
    date = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    project_id = models.ForeignKey(Project)
    stage = models.IntegerField(choices=(
        (1, 'Envision'),
        (2, 'Create'), 
        (3, 'Improve'),
        ), default = 1)
    status = models.CharField(max_length=50, null=True, blank=True)
    comment = models.TextField(null=True, blank=True)

class CheckInEntry(models.Model):
    checkIn_id = models.ForeignKey(CheckIn)
    attribute = models.CharField(choices=(
        ('FTO', 'Full Time Owner'), 
        ('BT', 'Balanced Team'), 
        ('SU', 'Shared Understanding'),
        ('VM', 'Value and Metrics'),
        ('EED', 'End-to-End Demo'),
        ('RM', 'Readme'),
        ('D', 'Dependencies'),
        ('V', 'Velocity'),
        ('O', 'Overview')
    ), max_length=3)
    colour = models.IntegerField(choices = (
        (0, 'grey'),
        (1, 'red'), 
        (2, 'yellow'), 
        (3, 'green'),
    ), default=0)
    comment = models.TextField(null=True, blank=True)

class UsersPerProject(models.Model):
    user_id = models.ForeignKey(User)
    project_id = models.ForeignKey(Project)

class Token(models.Model):
    token = models.TextField(null=False)
    token_type = models.CharField(max_length=50, null=False)
    expires_in = models.IntegerField()
    time_obtained = models.DateTimeField(auto_now_add=True)

class Staff(models.Model):
    username = models.CharField(max_length=40, null=True, blank=True)
    full_name = models.CharField(max_length=60, null=True)
    is_active = models.BooleanField(default=True)

phm/forms.py
from django import forms
from phm.models import Project, CheckIn, CheckInEntry
from django.core.exceptions import ObjectDoesNotExist

class GetProjectForm(forms.ModelForm):
    name = forms.CharField(
        label="Search projects",
        max_length=30,
        widget=forms.TextInput(attrs={
            "class": "text project-search-box",
            "placeholder": "Find a project by name"
        })
    )

    class Meta:
        model = Project
        fields = ['name']

class ProjectForm(forms.ModelForm):
    name = forms.CharField(
        label='Project Name:',
        max_length=30,
        widget=forms.TextInput(attrs={'class': 'text', 'className': 'project-name', 'data-aui-validation-field': '', 'data-aui-validation-required': 'required', "data-aui-notification-field": ""})
    )
    link = forms.CharField(
        label='Project website',
        widget=forms.TextInput(attrs={'class': 'text', 'className': 'project-link', 'data-aui-validation-field': '', 'data-aui-validation-required': 'required', "data-aui-notification-field": "", 'placeholder': 'Add a link to EAC'}),
    )
    department = forms.CharField(
        label='Department:',
        max_length=60,
        widget=forms.TextInput(attrs={'class': 'text', 'className': 'project-department'}),
        required=False
    )
    description = forms.CharField(
        label='Description:',
        widget=forms.Textarea(attrs={'class': 'textarea', 'className': 'project-description', 'placeholder': 'Add a description', 'rows': 3}),
        required=False
    )
    ownerInput = forms.CharField(
        label='Project owner:',
        max_length=60,
        widget=forms.TextInput(attrs={'class': 'text', 'className': 'project-owner', 'overrideField': True})
    )
    sponsorInput = forms.CharField(
        label='Project sponsor:',
        max_length=60,
        widget=forms.TextInput(attrs={'class': 'text', 'className': 'project-sponsor', 'overrideField': True})
    )
    memberInput = forms.CharField(
        label='Additional members:',
        max_length=60,
        widget=forms.TextInput(attrs={'class': 'text', 'className': 'project-members'}),
        required=False
    )
    members = forms.MultipleChoiceField(
        label='Members',
        widget=forms.SelectMultiple(attrs={'className': 'project-members-list', 'overrideField': True}),
        required=False
    )

    class Meta:
        model = Project
        fields = ['name', 'department', 'description', 'ownerInput', 'sponsorInput', 'memberInput', 'members']

class CheckInForm(forms.ModelForm):
    project_id = forms.CharField(
        label='Project',
        max_length=30,
        widget=forms.TextInput(attrs={'class': 'text disabled-with-border'})
        )
    stage = forms.ChoiceField(
        label='Stage',
        choices=(
            (1, 'Envision'),
            (2, 'Create'),
            (3, 'Improve'),
        ), 
        widget=forms.Select(attrs={'class': 'select disabled-with-border'})
        )
    status = forms.CharField(
        label='Status',
        max_length=50,
        widget=forms.TextInput(attrs={'class': 'text disabled-with-border', 'placeholder': 'E.g. Active, Roadmapped'}),
        required=False
        )
    comment = forms.CharField(
        label='Comment',
        max_length=140,
        widget=forms.Textarea(attrs={
            'class': 'textarea medium-field disabled-with-border',
            'placeholder': 'Add a comment',
            'rows': 3}),
        required=False
        )

    def clean_project_id(self):
        proj_name = self.cleaned_data['project_id']
        try:
            project = Project.objects.get(name=proj_name)
            return project
        except ObjectDoesNotExist:
            raise forms.ValidationError("Project doesn't exist")

    class Meta:
        model = CheckIn
        fields = ['project_id', 'stage', 'status', 'comment']

class CheckInAttributeForm(forms.ModelForm):
    checkIn_id = forms.CharField(widget=forms.HiddenInput())
    attribute = forms.CharField(widget=forms.HiddenInput())
    colour = forms.ChoiceField(
        label="Health",
        choices=((1, 'Unhealthy'),
            (2, 'Moderate'),
            (3, 'Healthy')),
        widget=forms.RadioSelect(attrs={"class":"circle-radio disabled-without-border"}))
    comment = forms.CharField(
        label='Comment',
        max_length=140,
        widget=forms.Textarea(attrs={
            'class': 'textarea disabled-without-border',
            'placeholder': "Comment. Any Changes? What worked or didn't work",
            'rows': 4}),
        required=False
        )

    def clean_checkIn_id(self):
        checkin_id = self.cleaned_data['checkIn_id']
        try:
            id = int(checkin_id)
            checkin = CheckIn.objects.get(id=checkin_id)
            return checkin
        except (ObjectDoesNotExist, ValueError):
            raise forms.ValidationError("Check-in doesn't exist")

    class Meta:
        model = CheckInEntry
        fields = ['checkIn_id', 'attribute', 'colour', 'comment']

phm/templates/about.html
{% extends "index.html" %}

{% block title %}About the Project Health Monitor{% endblock %}

{% block pageheading %}About the Project Health Monitor{% endblock %}

{% block content %}
    <div class="about-text">
        <p>Use the Health Monitor to check on your project and team health at any time throughout your project.
            The Health Monitor is all about helping you know what success looks like, how to get there, and how to get
            back on track if you need to. How you and your team do your health check is up to you.</p>
        <p>Each health check measures your project's health in the following <b>8 areas:</b></p>
    </div>

    <table class="about-table">
        {%  for a1, a2 in attribute_pairs %}
            <tr>
                <td>
                  <h4>{{ a1.1 }}</h4>
                  <p>{{ a1.2 }}</p>
                </td>
                <td>
                  <h4>{{ a2.1 }}</h4>
                  <p>{{ a2.2 }}</p>
                </td>
            </tr>
        {%  endfor %}
        <tr>
            <td colspan="2">
                <h4 class="center">{{ overview.1 }}</h4>
                <p class="center">{{ overview.2 }}</p>
            </td>
        </tr>
    </table>

    {% block pageJS %}
        <script src="/static/js/about.js"></script>
    {%  endblock %}

{% endblock %}

phm/templates/authenticate.html
{% extends "index.html" %}

{% block title %}Authenticate{% endblock %}

{% block pageheading %}Signup or Login{% endblock %}

{% block content %}
<div align="center">
  <p></p>
  {% if user.is_authenticated %}
    <p>Hello, {{ user.email }}! You are currently logged in. Click the button at the top right to logout.</p>
  {% else %}
    {% if error %}
    <div class="aui-message aui-message-error">
      <p class="title">
        <strong>Error</strong>
      </p>
      <p>{{ error }}</p>
    </div>
    {% endif %}

    <p>Authenticate with Google to add and track your projects.</p>
    <p>
      <a class="aui-button aui-button-primary home-button" href="{{ auth_endpoint }}response_type=token&client_id={{ client_id }}&redirect_uri={{ redirect_uri }}&scope={{ scope }}">Authenticate</a>
    </p>
  {% endif %}
</div>
{% endblock %}

phm/templates/checkin.html
{% extends "index.html" %}

{% block title %}Create a health check{% endblock %}

{% block pageheading %}
    {{ title }}
    {% if view_only %}
          <div class="aui-toolbar2 float-right" role="toolbar">
              <div class="aui-toolbar2-inner">
                  <div class="aui-item aui-buttons">
                      <input class="aui-button" type="reset" value="Edit" id="checkin-edit-button" />
                      {%  if  checkIn_id %}
                          <a class="aui-button" href="/phm/project?name={{ checkIn_id.project_id.name }}">Back to project</a>
                      {%  endif %}
                  </div>
              </div>
          </div>
    {% endif %}
{% endblock %}

{% block content %}

<div class="checkin-container" value="{{checkIn_id}}">
    <h2> Health check details</h2>
    <form action="#" method="post" id="addcheckinAttribute" class="aui">
        {% csrf_token %}
        <input id="checkinId" type="hidden" value="{{ checkIn_id }}">
        <fieldset class="form-medium checkin-form-main-content"> {# to make it aligned with the checkin entry boxes #}
            {% for field in checkin_form %}
              <div class="field-group">
                  <label for="{{ field.id_for_label }}">{{field.label_tag}}
                  {% if field.id_for_label == 'id_project_id' or field.id_for_label == 'id_stage' %}
                    <span class="aui-icon icon-required"></span>
                  {% endif %}
                  </label>
                  {{ field }}
                  {% for error in field.errors %}
                  <div class="error">
                    {{ error }}
                  </div>
                  {% endfor %}
              </div>
            {% endfor %}
        </fieldset>

        <h2> Project health</h2>
        <p><a href="/phm/about">Learn about the areas</a></p>

        {{ formset.management_form }}
        <div class="checkin-group">
            {% for form, attribute in content %}
                <div class="checkin-item {{ form.attribute.value.0 }}">
                    {{ form.checkIn_id }}
                    {{ form.attribute }}
                    <div class="checkin-item-header">
                        <h4 class="checkin-attr-header">{{attribute.1}} </h4>
                        <div class="checkin-options-group">
                            {%  if form.errors.colour.0 %}
                                <span class="errortext">Please select health</span>
                            {%  endif %}
                            <div class="checkin-options">
                                <p>Health</p>
                                <div class="health-buttons {{attribute.0}}-health-buttons">
                                    {{ form.colour }}
                                </div>
                            </div>
                        </div>
                        <fieldset>
                            <div class="checkin-item-body">
                                {{ form.comment }}
                            </div>
                        </fieldset>
                    </div>
                </div>
            {% endfor %}
        <div class="buttons-container {%  if view_only %}hidden{% endif %}">
          <input class="aui-button checkin-button aui-button-primary float-right" style="
              margin-left: 10px;
              " type="submit" value="{{ submit_text }}" id="checkin-submit-button" />
            <input class="aui-button checkin-button float-right" type="reset" value="Clear" id="checkin-clear-button" />
        </div>
    </form>
</div>
{% block pageJS %}
<script src="/static/js/checkin.js"></script>
{%  endblock %}
{% endblock %}

phm/templates/checkin_past.html
{% extends "index.html" %}

{% block title %}{{checkin.project_id.name}}{% endblock %} 

{% block pageheading %}{{project.name}} - Health Overview {% endblock %}

{% block content %}

<table class="aui">
    <thead>
        <tr>
            <th id="ci_attr">Area</th>
            {% for checkin in checkins.keys %}
                <th id="ci_header-{{checkin.id}}">{{checkin.date}}</th>
            {% endfor %}
        </tr>
    </thead>
    <tbody>
    {% for attr, attr_long, attr_desc in attributes %}
        <tr>
            <td headers="ci_attr">{{attr_long}}</td> 

            {% for checkin, ci_attrs in checkins.items %}
                {% if ci_attrs.items|length != 0 %}
                {% if attr not in ci_attrs.items %}
                    <td headers="ci_header-{{checkin.id}}">
                        <div class="block grey"></div>
                    </td>
                {% endif %}

                {% for a,e in ci_attrs.items %}
                {% if a == attr %}
                    <td headers="ci_header-{{checkin.id}}">
                        <div class="block {{e.get_colour_display}}"></div>
                    </td>
                {% endif %}
                {% endfor %}
                {% endif %}

            {% endfor %}
        </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

phm/templates/footer.html
<footer id="footer" role="contentinfo">
    <section class="footer-body">
        <ul id="aui-footer-list">
            <li>Made with ❤ in Sydney, Australia</li>
            <li><a href="https://bitbucket.org/tianyupu/health-monitor/issues/new">Report a bug</a></li>
        </ul>
        <div id="footer-logo"><a href="http://www.atlassian.com">Atlassian</a></div>
    </section>
</footer>

phm/templates/header.html
<header id="header" role="banner">
  <nav class="aui-header aui-dropdown2-trigger-group" role="navigation" data-aui-responsive="true">
    <div class="aui-header-primary">
      <h1 id="logo" class="aui-header-logo">
        <a href="/"><img src="/static/images/logo-projecthealthmonitor.png"/></a>
      </h1>
      <ul class="aui-nav">
        <!-- Projects tab -->
        <li>
          <a id="projects-tab" href="#" aria-haspopup="true" class="aui-dropdown2-trigger aui-alignment-target aui-alignment-abutted aui-alignment-abutted-left aui-alignment-element-attached-top aui-alignment-element-attached-left aui-alignment-target-attached-bottom aui-alignment-target-attached-left aui-alignment-out-of-bounds aui-alignment-out-of-bounds-bottom" aria-controls="dropdown2-jira3" aria-expanded="false" resolved="">Projects</a>
          <div class="aui-dropdown2 aui-style-default aui-dropdown2-in-header aui-layer aui-alignment-element aui-alignment-side-bottom aui-alignment-snap-left aui-alignment-abutted aui-alignment-abutted-left aui-alignment-element-attached-top aui-alignment-element-attached-left aui-alignment-target-attached-bottom aui-alignment-target-attached-left aui-alignment-side-bottom aui-alignment-snap-left aui-alignment-out-of-bounds aui-alignment-out-of-bounds-bottom" id="dropdown2-jira3" aria-hidden="true" resolved="" data-aui-alignment="bottom auto" data-aui-alignment-static="true" style="z-index: 3000; top: 0px; left: 0px; position: absolute; transform: translateX(407px) translateY(725px) translateZ(0px);">
            <div class="aui-dropdown2-section">
              <ul>
                <li><a href="/phm/addproject">Add Project</a></li>
                <li><a href="/phm/viewproject">View Projects</a></li>
              </ul>
            </div>
            {% if user.is_authenticated %}
              <div class="aui-dropdown2-section" id="favourite-projects-container"> <!-- favourite projects retrieved via AJAX -->
              </div>
            {% endif %}
          </div>
        </li>
        <li><a href="/phm/about">About</a></li>
        <li><a class="aui-button aui-button-primary" href="/phm/addcheckin">Create health check</a></li>
      </ul>
    </div>
    <div class="aui-header-secondary">
      <ul class="aui-nav __skate" resolved>
        {% if user.is_authenticated %}
        <li>
          <a class="aui-dropdown2-trigger" aria-haspopup="true" aria-owns="user-options-content" aria-controls="user-options-content">
            <span class="aui-avatar aui-avatar-small">
              <img id="active-user-avatar" src="/static/images/default-avatar.png">
            </span>
          </a>
          <div id="user-options-content" class="aui-dropdown2 aui-style-default">
            <ul class="aui-list-truncate">
              <li><a href="/phm/logout">Log out {{ user.email }}</a></li>
            </ul>
          </div>
        </li>
        {% else %}
        <li><a class="aui-nav-link" href="/phm/auth">Signup or Login</a></li>
        {% endif %}
      </ul>
    </div>
  </div>
  </nav>
</header>
<span id="username" value="{{ user.username }}"></span>
<script src="/static/js/header.js"></script>

phm/templates/index.html
<!doctype html>
    <head>
        <title>{% block title %}Home{% endblock %} - Health Monitor App</title>
        <link rel="shortcut icon" href="/static/images/favicon.ico" />

        <!-- Required for some dependencies -->
        <script src="/static/js/lib/almond.js"></script>

        <!-- Core AUI CSS and JS -->
        <link rel="stylesheet" href="/static/css/styles.css" media="screen">
        <link rel="stylesheet" href="/static/css/index.css" media="screen">
        <link rel="stylesheet" href="/static/css/view-project.css" media="screen">
        <link rel="stylesheet" href="/static/css/filters.css" media="screen">
        <link rel="stylesheet" href="/static/css/checkin.css" media="screen">
        <link rel="stylesheet" href="/static/css/health-buttons.css" media="screen">
        <link rel="stylesheet" href="/static/css/about-page.css" media="screen">
        <link rel="stylesheet" href="/static/css/project-form.css" media="screen">
        <link rel="stylesheet" href="/static/css/lib/aui.min.css" media="all">
        <script src="/static/js/lib/jquery.min.js"></script>
        <script src="/static/js/lib/aui.min.js"></script>

        <!--AMD Loader, required for experimental components-->
        <link rel="stylesheet" href="/static/css/lib/aui-experimental.min.css" media="all">
        <script src="/static/js/lib/aui-experimental.min.js"></script>

        <!-- Extra AUI date-picker component -->
        <script src="/static/js/lib/aui-datepicker.min.js"></script>

        <!-- IE10 polyfill for the placeholder attribute in input tags -->
        <script src="/static/js/lib/placeholders.min.js"></script>

        <!-- Our own js that will be used a lot -->
        <!-- Js to import before the other stuff_-->
        {% block beforeJS %}{% endblock %}
        <script src="/static/js/scripts.js"></script>
        <script src="/static/js/filters.js"></script>
        <!-- Js to import before the other stuff_-->
        {% block afterJS %}{% endblock %}
    </head>

    <body class="aui-page-hybrid">
        {% include 'header.html' %}
        <section class="content" role="main">
            <div class="aui-page-panel">
            {% block sidebar %}{% endblock %}
                <div class="aui-page-panel-inner">
                    <section class="aui-page-panel-content">
                        <h1 align="center" style="color:#205081">
                            {% block pageheading %}
                                <img src="/static/images/logo.svg" style="vertical-align: middle; margin-bottom:5px">Project Health Monitor
                            {% endblock %}
                        </h1>

                        {% block content %}
                            <div align="center">
                                <img class="hero-image" width=350px src="/static/images/personas-illustration.png">
                                <br>
                                <div>
                                    <p><a class="aui-button home-button" href="/phm/allprojects?view=mine">My projects</a></p>
                                    <p><a class="aui-button home-button" href="/phm/allprojects?view=all">All projects</a></p>
                                    <p><a class="aui-button aui-button-primary home-button" href="/phm/addproject">Create a project</a>
                                    <p></p>
                                </div>
                                <div class="divider small-divider"></div>
                                <div class="favourite-projects">
                                    <h2 align="center" style="color:#3572b0">Favourite projects</h2>
                                    {% if favourites|length == 0 %}
                                        <p class="no-content">You do not have any favourite projects. To make a project a favourite, click on the star in the view project page.</p>
                                    {% endif %}
                                    <div class="home-page-project-list">
                                        {% for fav in favourites %}
                                            <div class="{{ favourites_class }}"><a class="aui-button project-button" href="/phm/project?name={{ fav.name }}">{{ fav.name }}</a></div>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                            {%  block pageJS %}{% endblock %}
                        {% endblock %}
                    </section>
                </div>
            </div>
        </section>
        {% include 'footer.html' %}
    </body>
</html>

phm/templates/nav-favourites-list.html
<strong>Favourite Projects</strong>
<ul>
{% if favourites %}
  {% for favourite in favourites %}
    <li><a href="/phm/project?name={{ favourite.name }}">{{ favourite.name }}</a></li>
  {% endfor %}
{% else %}
  <li><a class="no-content">You don't have any favourite projects.</a></li>
{% endif %}
</ul>

phm/templates/project-form.html
{% extends "index.html" %}

{% block title %}Project{% endblock %}

{% block pageheading %}
  <div class="heading">{{ title }}</div>
{% endblock %}

{% block content %}
    <form action="#" method="post" id="projectform" class="aui">
        {% csrf_token %}
        <fieldset class="project-form-fieldset">
            <div class="project-form-fields field-group project-name">
                <label>{{form.name.label}}<span class="aui-icon icon-required"></span></label>
                {{ form.name }}
                <div class="error">
                    {{ form.name.errors}}
                </div>
            </div>
            <div class="project-form-fields field-group project-name">
                <label>{{form.link.label}}<span class="aui-icon icon-required"></span></label>
                {{ form.link }}
                <div class="error">
                    {{ form.link.errors}}
                </div>
            </div>
            <div class="project-form-fields field-group project-department">
                <label>{{form.department.label}}<span class="aui-icon icon-required"></span></label>
                {{ form.department }}
                <div class="error">
                    {{ form.department.errors }}
                </div>
            </div>
            <div class="project-form-fields field-group project-description">
                <label>{{form.description.label}}</label>
                {{ form.description }}
                <div class="error">
                    {{ form.description.errors }}
                </div>
            </div>
            <div class="project-owner-sponsor-group">
                <div class="owner-sponsor-input">
                    <div class="project-form-fields field-group project-owner">
                        <label>{{form.ownerInput.label}}<span class="aui-icon icon-required"></span></label>
                        {{ form.ownerInput }}
                        <div class="error">
                            {{ form.ownerInput.errors }}
                        </div>
                    </div>
                    <div class="project-form-fields field-group project-sponsor">
                        <label>{{form.sponsorInput.label}}<span class="aui-icon icon-required"></span></label>
                        {{ form.sponsorInput }}
                        <div class="error">
                            {{ form.sponsorInput.errors }}
                        </div>
                    </div>
                </div>
                <div class="owner-sponsor-avatars">
                    <ul class="squares no-wrap" id="ownerInput_id" name="ownerInput"></ul>
                    <select multiple="multiple" id="ownerSelect_id" name="ownerInput" hidden="true"></select>
                    <ul class="squares no-wrap" id="sponsorInput_id" name="sponsorInput"></ul>
                    <select multiple="multiple" id="sponsorSelect_id" name="sponsorInput" hidden="true"></select>
                </div>
            </div>

            <div class="project-member-group">
                <div class="member-input">
                    <div class="project-form-fields field-group project-members">
                        <label>{{form.memberInput.label}}</label>
                        {{ form.memberInput }}
                        <div class="error">
                            {{ form.memberInput.errors }}
                        </div>
                    </div>
                    <br>
                </div>
                <div class="member-avatars">
                    <ul class="squares no-wrap" id="memberList" name="members"></ul>
                    <select multiple="multiple" id="id_members" name="members" hidden="true"></select>
                </div>
            </div>

            {% for member in members %}
                <span class="hidden project-member">{{ member }}</span>
            {% endfor %}

            <div class="buttons-container" align="right">
                <input class="aui-button aui-button-primary confirm" style="text-align:center" type="submit" value={{ buttonText }} id="save_btn" />
            </div>
        </fieldset>
    </form>
    {% block pageJS %}
    <script src="/static/js/project-form.js"></script>
    {%  endblock %}
{% endblock %}

phm/templates/sidebar.html
<div class="aui-sidebar repo-sidebar">
  <div class="aui-sidebar-wrapper" style="height: 720px; width: 100px;">
    <div class="aui-sidebar-body">
      <header class="aui-page-header">
      </header>
      <nav class="aui-navgroup aui-navgroup-vertical">
        <div class="aui-navgroup-inner">
          <div class="aui-sidebar-group aui-sidebar-group-tier-one repository-sections">
            <div class="aui-nav-heading">
              <div class="profile-picture profile-picture-small" style="float:none;margin-left:10px;
                {% if project.avatar %}
                background-image: url("{{project.avatar.path}}");
                {% endif %}
                "></div>
            </div>
          </div>
          <div class="aui-sidebar-group aui-sidebar-group-tier-one repository-settings">
            <div class="aui-nav-heading">
            </div>
            <ul class="aui-nav" style="text-align:center;">
              <li><span class="aui-icon aui-icon-large aui-iconfont-devtools-file-commented" style="color:#205081;padding-bottom:10px">Health checks</span>
              <li><span class="aui-icon aui-icon-large aui-iconfont-configure" style="color:#205081;padding-bottom:10px">Configure</span>
            </ul>
          </div>
        </div>
      </nav>
    </div>
    <div class="aui-sidebar-footer">
      <a class="aui-sidebar-toggle aui-sidebar-footer-tipsy aui-button aui-button-subtle"><span class="aui-icon"></span></a>
    </div>
  </div>
</div>